### ISSUE TITLE
Suggestion to enhance 'enabling dark theme' in README.md by add 'chmod +x'

### ISSUE THREAD

**Issue by lphoogenboom** [veyselerden/elementaryos-dark-theme-enabler-script#2]
My suggestion is to change
```` git clone https://github.com/veyselerden/elementaryos-dark-theme-enabler-script.git && cd elementaryos-dark-theme-enabler-script && ./enable-dark-theme.sh ````
into
````git clone https://github.com/veyselerden/elementaryos-dark-theme-enabler-script.git && cd elementaryos-dark-theme-enabler-script && chmod +x enable-dark-theme-sh && ./enable-dark-theme.sh ````

i.e. adding 
````  chmod +x enable-dark-theme-sh  ````
for even further automation and fool proofness

Thanks for the script. Cheers lads.

**Comment by veyselerden** [comment]
Done! Thanks for suggestion :)
