### ISSUE TITLE
Script doesn't make the app menu and notifications center dark

### ISSUE THREAD

**Issue by michaljenicek** [veyselerden/elementaryos-dark-theme-enabler-script#4]
Hi, I'm having problems with your script, when I run the script, everything completes successfully but after relog app menu and notifications center (the whole top panel) stays in light theme.

Do you have any ideas what could be the problem?

I use current elementary OS 5.1.7 Hera.

Thank you.

**Comment by veyselerden** [comment]
Yeah it seems like something is broken with recent updates. I think we need to wait for 6.0 to come.
